# Generated by Django 5.2.8 on 2026-07-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
