# Generated by Django 5.2.8 on 2026-09-02 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0003_alter_roleassignment_unique_together_and_more"),
        ("identity", "0004_seed_bible_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membershiptransfer",
            index=models.Index(
                fields=["-transferred_at"], name="mtransfer_time_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershiptransfer",
            index=models.Index(
                fields=["user", "-transferred_at"], name="mtransfer_user_time_idx"
            ),
        ),
    ]
