# Generated by Django 5.2.8 on 2026-01-20 01:08

from django.db import migrations
from django.utils import timezone


def migrate_tickets_to_registrations(apps, schema_editor):
    """
    Migrate data from tickets.Ticket to events.EventRegistration.
    
    Field mapping based on actual Ticket model:
    - full_name → attendee_name
    - age → attendee_age
    - phone → attendee_phone
    - email → attendee_email
    - parent_name, parent_phone, parent_email → guardian_*
    - emergency_contact, emergency_phone → emergency_contact_*
    
    Note: Handles duplicate emails by appending ticket_id if email already exists.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    Event = apps.get_model('events', 'Event')
    EventRegistration = apps.get_model('events', 'EventRegistration')
    
    # Check if there are any tickets to migrate
    if not Ticket.objects.exists():
        print("No tickets to migrate.")
        return
    
    # Create a default event to hold migrated registrations
    default_event, created = Event.objects.get_or_create(
        slug='legacy-campout-2025',
        defaults={
            'title': 'Region 63 Teenagers Camp Out 2025 (Legacy)',
            'event_type': 'campout',
            'description': 'Migrated event from legacy ticketing system.',
            'short_description': 'Legacy event for migrated registrations.',
            'start_datetime': timezone.now(),
            'end_datetime': timezone.now(),
            'venue': 'See registration details',
            'registration_status': 'closed',
            'is_free': False,
            'price': 15000.00,
            'status': 'published',
        }
    )
    
    # Mapping from Ticket status to EventRegistration status
    status_mapping = {
        'pending': 'pending',
        'approved': 'confirmed',
        'rejected': 'cancelled',
        'cancelled': 'cancelled',
    }
    
    # Mapping from Ticket payment status to EventRegistration payment status
    payment_status_mapping = {
        'unpaid': 'pending',
        'paid': 'paid',
        'verification_pending': 'pending',
    }
    
    migrated_count = 0
    seen_emails = set()
    
    # Get existing registration emails for this event
    existing_emails = set(
        EventRegistration.objects.filter(event=default_event)
        .values_list('attendee_email', flat=True)
    )
    seen_emails.update(existing_emails)
    
    # Migrate each ticket
    for ticket in Ticket.objects.all():
        # Check if already migrated
        existing = EventRegistration.objects.filter(
            registration_id=f"LEG-{ticket.ticket_id}"
        ).exists()
        if existing:
            continue
        
        # Handle duplicate emails by making them unique
        base_email = (ticket.email or '').strip().lower()
        attendee_email = base_email
        
        if not attendee_email:
            # Generate unique placeholder email
            attendee_email = f"no-email-{ticket.ticket_id}@legacy.local"
        elif attendee_email in seen_emails:
            # Make duplicate email unique by appending ticket_id
            attendee_email = f"{ticket.ticket_id}-{base_email}"
        
        seen_emails.add(attendee_email)
        
        # Create EventRegistration using actual Ticket fields
        registration = EventRegistration.objects.create(
            event=default_event,
            
            # Attendee info (from Ticket)
            attendee_name=ticket.full_name or 'Unknown',
            attendee_email=attendee_email,
            attendee_phone=ticket.phone or '',
            attendee_age=ticket.age or 0,
            attendee_gender=ticket.gender or '',
            attendee_date_of_birth=ticket.date_of_birth,
            attendee_category=ticket.category or '',
            
            # Church hierarchy
            attendee_province=ticket.province or 'regional_hq',
            attendee_zone=ticket.zone or '',
            attendee_area=ticket.area or '',
            attendee_parish=ticket.parish or '',
            attendee_department=ticket.department or '',
            
            # Guardian info (from parent_* fields)
            guardian_name=ticket.parent_name or '',
            guardian_phone=ticket.parent_phone or '',
            guardian_email=ticket.parent_email or '',
            guardian_relationship=ticket.parent_relationship or '',
            guardian_consent=True,  # Assumed if they registered
            
            # Emergency contact
            emergency_contact_name=ticket.emergency_contact or '',
            emergency_contact_phone=ticket.emergency_phone or '',
            emergency_contact_relationship=ticket.emergency_relationship or '',
            
            # Medical info
            medical_conditions=ticket.medical_conditions or '',
            allergies='',  # Not in original Ticket
            medications=ticket.medications or '',
            dietary_restrictions=ticket.dietary_restrictions or '',
            special_needs='',
            
            # Status
            status=status_mapping.get(ticket.status, 'pending'),
            payment_status=payment_status_mapping.get(ticket.payment_status, 'pending'),
            registration_type='bulk',  # Mark as bulk since it's from legacy
            
            # Payment details
            amount_due=None,  # Not tracked in old system
            amount_paid=None,
            proof_of_payment=ticket.proof_of_payment.name if ticket.proof_of_payment else None,
            
            # Approval info
            approved_at=ticket.approved_at,
            
            # QR code
            qr_code=ticket.qr_code.name if ticket.qr_code else None,
            
            # Notes
            notes=ticket.notes or '',
            internal_notes=f"Migrated from legacy ticket: {ticket.ticket_id}. Original email: {ticket.email or 'N/A'}",
        )
        
        # Set the registration_id manually (bypass auto-generation)
        registration.registration_id = f"LEG-{ticket.ticket_id}"
        registration.save(update_fields=['registration_id'])
        
        migrated_count += 1
    
    # Update event stats
    default_event.registration_count = EventRegistration.objects.filter(
        event=default_event
    ).count()
    default_event.checked_in_count = EventRegistration.objects.filter(
        event=default_event, 
        status='checked_in'
    ).count()
    default_event.save()
    
    print(f"Migrated {migrated_count} tickets to EventRegistrations")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete migrated registrations.
    """
    EventRegistration = apps.get_model('events', 'EventRegistration')
    Event = apps.get_model('events', 'Event')
    
    # Delete legacy registrations
    deleted, _ = EventRegistration.objects.filter(
        registration_id__startswith='LEG-'
    ).delete()
    print(f"Deleted {deleted} legacy registrations")
    
    # Delete legacy event
    Event.objects.filter(slug='legacy-campout-2025').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_tickets_to_registrations,
            reverse_code=reverse_migration,
        ),
    ]
