# Generated by Django 5.2.8 on 2026-02-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_migrate_tickets_to_registrations"),
        ("profiles", "0007_add_parish_and_guardian_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_registrations",
                to="profiles.teenprofile",
            ),
        ),
    ]
