# Generated by Django 5.2.8 on 2026-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_fix_event_registration_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("waitlisted", "Waitlisted"),
                    ("checked_in", "Checked In"),
                    ("attended", "Attended"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
