# Generated by Django 5.2.8 on 2026-09-02 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_remove_event_target_provinces"),
        ("payments", "0002_alter_paymentplan_ticket_category"),
        ("profiles", "0010_drop_orphaned_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventregistration",
            name="events_even_registr_0b4b2b_idx",
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["-created_at"], name="evreg_created_desc_idx"),
        ),
    ]
