# Generated by Django 5.2.8 on 2026-09-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0009_remove_eventregistration_events_even_registr_0b4b2b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
