# Generated by Django 5.2.8 on 2026-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_bedspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="pay_code",
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True
            ),
        ),
    ]
