# Generated by Django 5.2.8 on 2026-07-14 12:38

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("gentle", "Gentle (morning only)"),
                            ("standard", "Standard (morning + evening)"),
                            ("committed", "Committed (full ladder)"),
                        ],
                        default="standard",
                        max_length=16,
                    ),
                ),
                ("habit_reminders_enabled", models.BooleanField(default=True)),
                ("event_notifications_enabled", models.BooleanField(default=True)),
                ("announcements_enabled", models.BooleanField(default=True)),
                ("system_notifications_enabled", models.BooleanField(default=True)),
                ("morning_rung_enabled", models.BooleanField(default=True)),
                ("afternoon_rung_enabled", models.BooleanField(default=True)),
                ("evening_rung_enabled", models.BooleanField(default=True)),
                ("final_rung_enabled", models.BooleanField(default=True)),
                ("morning_at", models.TimeField(default=datetime.time(6, 30))),
                ("afternoon_at", models.TimeField(default=datetime.time(13, 30))),
                ("evening_at", models.TimeField(default=datetime.time(18, 30))),
                ("final_at", models.TimeField(default=datetime.time(20, 45))),
                ("quiet_hours_start", models.TimeField(default=datetime.time(21, 30))),
                ("quiet_hours_end", models.TimeField(default=datetime.time(6, 0))),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=64)),
                (
                    "consecutive_ignored_days",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("last_stepped_down_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("habit_reminder", "Habit reminder"),
                            ("event", "Event"),
                            ("announcement", "Announcement"),
                            ("system", "System"),
                            ("transactional", "Transactional"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "rung",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("final", "Final"),
                        ],
                        help_text="Set on habit reminders — which rung of the ladder this was.",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("deep_link", models.CharField(blank=True, max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_47e85c_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type", "-created_at"],
                        name="notificatio_user_id_17cab8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key__gt", "")),
                        fields=("user", "dedupe_key"),
                        name="notifications_uniq_dedupe_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(max_length=500, unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_1159a5_idx",
                    )
                ],
            },
        ),
    ]
