// GENERATED by scripts/fetch-site-art.mjs — do not edit.
// Run `npm run art` after adding a piece to that script.

import object_bell from './objects/bell.webp';
import object_bookmarkFav from './objects/bookmark-fav.webp';
import object_bookmark from './objects/bookmark.webp';
import object_boy from './objects/boy.webp';
import object_bulb from './objects/bulb.webp';
import object_calendar from './objects/calendar.webp';
import object_callIn from './objects/call-in.webp';
import object_camera from './objects/camera.webp';
import object_candle from './objects/candle.webp';
import object_chatBubble from './objects/chat-bubble.webp';
import object_chatText from './objects/chat-text.webp';
import object_clock from './objects/clock.webp';
import object_colorPalette from './objects/color-palette.webp';
import object_crown from './objects/crown.webp';
import object_cup from './objects/cup.webp';
import object_fileText from './objects/file-text.webp';
import object_fire from './objects/fire.webp';
import object_flag from './objects/flag.webp';
import object_flash from './objects/flash.webp';
import object_gift from './objects/gift.webp';
import object_girl from './objects/girl.webp';
import object_headphone from './objects/headphone.webp';
import object_heart from './objects/heart.webp';
import object_key from './objects/key.webp';
import object_leaf from './objects/leaf.webp';
import object_link from './objects/link.webp';
import object_location from './objects/location.webp';
import object_lock from './objects/lock.webp';
import object_mail from './objects/mail.webp';
import object_mapPin from './objects/map-pin.webp';
import object_medal from './objects/medal.webp';
import object_megaphone from './objects/megaphone.webp';
import object_message from './objects/message.webp';
import object_mic from './objects/mic.webp';
import object_mobile from './objects/mobile.webp';
import object_moon from './objects/moon.webp';
import object_music from './objects/music.webp';
import object_notebook from './objects/notebook.webp';
import object_notifyHeart from './objects/notify-heart.webp';
import object_pencil from './objects/pencil.webp';
import object_picture from './objects/picture.webp';
import object_play from './objects/play.webp';
import object_puzzle from './objects/puzzle.webp';
import object_ribbon from './objects/ribbon.webp';
import object_rocket from './objects/rocket.webp';
import object_shield from './objects/shield.webp';
import object_star from './objects/star.webp';
import object_sun from './objects/sun.webp';
import object_target from './objects/target.webp';
import object_teaCup from './objects/tea-cup.webp';
import object_thumbUp from './objects/thumb-up.webp';
import object_tick from './objects/tick.webp';
import object_travel from './objects/travel.webp';
import object_trophy from './objects/trophy.webp';
import object_videoCam from './objects/video-cam.webp';
import object_wifi from './objects/wifi.webp';
import object_zoom from './objects/zoom.webp';

import doodle_ballet from './illustrations/ballet.svg';
import doodle_chilling from './illustrations/chilling.svg';
import doodle_clumsy from './illustrations/clumsy.svg';
import doodle_dancing from './illustrations/dancing.svg';
import doodle_dogJump from './illustrations/dog-jump.svg';
import doodle_float from './illustrations/float.svg';
import doodle_groovy from './illustrations/groovy.svg';
import doodle_iceCream from './illustrations/ice-cream.svg';
import doodle_jumping from './illustrations/jumping.svg';
import doodle_laying from './illustrations/laying.svg';
import doodle_loving from './illustrations/loving.svg';
import doodle_meditating from './illustrations/meditating.svg';
import doodle_moshing from './illustrations/moshing.svg';
import doodle_petting from './illustrations/petting.svg';
import doodle_plant from './illustrations/plant.svg';
import doodle_readingSide from './illustrations/reading-side.svg';
import doodle_reading from './illustrations/reading.svg';
import doodle_rollerSkating from './illustrations/roller-skating.svg';
import doodle_rolling from './illustrations/rolling.svg';
import doodle_running from './illustrations/running.svg';
import doodle_selfie from './illustrations/selfie.svg';
import doodle_sittingReading from './illustrations/sitting-reading.svg';
import doodle_sitting from './illustrations/sitting.svg';
import doodle_sleek from './illustrations/sleek.svg';
import doodle_strolling from './illustrations/strolling.svg';
import doodle_swinging from './illustrations/swinging.svg';
import doodle_unboxing from './illustrations/unboxing.svg';

/** 3D objects (3dicons, CC0). 400x400 WebP. */
export const OBJECTS = {
  bell: object_bell,
  bookmarkFav: object_bookmarkFav,
  bookmark: object_bookmark,
  boy: object_boy,
  bulb: object_bulb,
  calendar: object_calendar,
  callIn: object_callIn,
  camera: object_camera,
  candle: object_candle,
  chatBubble: object_chatBubble,
  chatText: object_chatText,
  clock: object_clock,
  colorPalette: object_colorPalette,
  crown: object_crown,
  cup: object_cup,
  fileText: object_fileText,
  fire: object_fire,
  flag: object_flag,
  flash: object_flash,
  gift: object_gift,
  girl: object_girl,
  headphone: object_headphone,
  heart: object_heart,
  key: object_key,
  leaf: object_leaf,
  link: object_link,
  location: object_location,
  lock: object_lock,
  mail: object_mail,
  mapPin: object_mapPin,
  medal: object_medal,
  megaphone: object_megaphone,
  message: object_message,
  mic: object_mic,
  mobile: object_mobile,
  moon: object_moon,
  music: object_music,
  notebook: object_notebook,
  notifyHeart: object_notifyHeart,
  pencil: object_pencil,
  picture: object_picture,
  play: object_play,
  puzzle: object_puzzle,
  ribbon: object_ribbon,
  rocket: object_rocket,
  shield: object_shield,
  star: object_star,
  sun: object_sun,
  target: object_target,
  teaCup: object_teaCup,
  thumbUp: object_thumbUp,
  tick: object_tick,
  travel: object_travel,
  trophy: object_trophy,
  videoCam: object_videoCam,
  wifi: object_wifi,
  zoom: object_zoom,
} as const;

/**
 * Each drawing sits inside a square art box. `inset` is how far it is pulled in
 * from that box’s edges, which is what gives every drawing its own proportions
 * without stretching it.
 */
export type Illustration = { src: string; inset: string };

/** Line drawings (Open Doodles, CC0), in the brand ink and green. */
export const ILLUSTRATIONS = {
  ballet: { src: doodle_ballet, inset: '10.76% 5%' },
  chilling: { src: doodle_chilling, inset: '21.28% 5%' },
  clumsy: { src: doodle_clumsy, inset: '14.26% 5%' },
  dancing: { src: doodle_dancing, inset: '11.98% 5%' },
  dogJump: { src: doodle_dogJump, inset: '13.69% 5%' },
  float: { src: doodle_float, inset: '17.91% 5%' },
  groovy: { src: doodle_groovy, inset: '13.27% 5%' },
  iceCream: { src: doodle_iceCream, inset: '5% 10.45%' },
  jumping: { src: doodle_jumping, inset: '13.51% 5%' },
  laying: { src: doodle_laying, inset: '26.08% 5%' },
  loving: { src: doodle_loving, inset: '17.83% 5%' },
  meditating: { src: doodle_meditating, inset: '15.42% 5%' },
  moshing: { src: doodle_moshing, inset: '5% 11.16%' },
  petting: { src: doodle_petting, inset: '5% 5.51%' },
  plant: { src: doodle_plant, inset: '7.87% 5%' },
  readingSide: { src: doodle_readingSide, inset: '22.15% 5%' },
  reading: { src: doodle_reading, inset: '5% 11.14%' },
  rollerSkating: { src: doodle_rollerSkating, inset: '16.24% 5%' },
  rolling: { src: doodle_rolling, inset: '14.88% 5%' },
  running: { src: doodle_running, inset: '20.18% 5%' },
  selfie: { src: doodle_selfie, inset: '5% 18.46%' },
  sittingReading: { src: doodle_sittingReading, inset: '14.28% 5%' },
  sitting: { src: doodle_sitting, inset: '8.46% 5%' },
  sleek: { src: doodle_sleek, inset: '15.46% 5%' },
  strolling: { src: doodle_strolling, inset: '6.45% 5%' },
  swinging: { src: doodle_swinging, inset: '7.73% 5%' },
  unboxing: { src: doodle_unboxing, inset: '14.83% 5%' },
} as const satisfies Record<string, Illustration>;
