# Generated by Django 5.2.8 on 2025-12-03 07:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="bulk_uploads/")),
                ("total_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Ticket ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                8, message="Age must be at least 8 years."
                            ),
                            django.core.validators.MaxValueValidator(
                                19, message="Age must not exceed 19 years."
                            ),
                        ]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pre_teens", "Pre-Teens (8-12)"),
                            ("teens", "Teens (13-19)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("province", models.CharField(max_length=255)),
                ("zone", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=255)),
                ("parish", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, verbose_name="Any medical conditions or allergies?"
                    ),
                ),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Current medications"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(blank=True, verbose_name="Dietary restrictions"),
                ),
                ("emergency_contact", models.CharField(max_length=255)),
                ("emergency_phone", models.CharField(max_length=20)),
                ("emergency_relationship", models.CharField(max_length=100)),
                ("parent_name", models.CharField(max_length=255)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=20)),
                ("parent_relationship", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any additional notes or comments"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("status_change", "Status Change"),
                            ("bulk_upload", "Bulk Upload"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tickets.bulkupload",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_id"], name="tickets_tic_ticket__5a4a00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_tic_status_0e5646_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["province"], name="tickets_tic_provinc_692fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category"], name="tickets_tic_categor_fc7dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["registered_by"], name="tickets_tic_registe_e5e9da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["registered_at"], name="tickets_tic_registe_35d076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["ticket", "timestamp"], name="tickets_tic_ticket__56257e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="tickets_tic_user_id_cffc8e_idx"
            ),
        ),
    ]
