# Generated by Django 5.2.8 on 2025-12-01 14:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file", models.FileField(upload_to="bulk_uploads/")),
                ("total_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(19),
                        ]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pre_teens", "Pre-Teens (8-12)"),
                            ("teens", "Teens (13-19)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("province", models.CharField(max_length=255)),
                ("zone", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=255)),
                ("parish", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("dietary_restrictions", models.TextField(blank=True, null=True)),
                ("emergency_contact", models.CharField(max_length=255)),
                ("emergency_phone", models.CharField(max_length=20)),
                ("emergency_relationship", models.CharField(max_length=100)),
                ("parent_name", models.CharField(max_length=255)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=20)),
                ("parent_relationship", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "ticket_pdf",
                    models.FileField(blank=True, null=True, upload_to="ticket_pdfs/"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="tickets_tic_status_0e5646_idx"
                    ),
                    models.Index(
                        fields=["province"], name="tickets_tic_provinc_692fc7_idx"
                    ),
                    models.Index(
                        fields=["registered_by"], name="tickets_tic_registe_e5e9da_idx"
                    ),
                    models.Index(
                        fields=["registered_at"], name="tickets_tic_registe_35d076_idx"
                    ),
                ],
            },
        ),
    ]
