# Generated by Django 5.2.8 on 2025-12-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="province",
            field=models.CharField(
                choices=[
                    ("province_1", "Province 1"),
                    ("province_2", "Province 2"),
                    ("province_3", "Province 3"),
                    ("province_4", "Province 4"),
                    ("province_5", "Province 5"),
                    ("province_6", "Province 6"),
                    ("province_7", "Province 7"),
                    ("province_8", "Province 8"),
                ],
                max_length=255,
            ),
        ),
    ]
