# Generated by Django 5.2.8 on 2025-12-01 15:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only staff can see this comment",
                        verbose_name="internal comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "ticket comment",
                "verbose_name_plural": "ticket comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="bulkupload",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "bulk upload",
                "verbose_name_plural": "bulk uploads",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-registered_at"],
                "permissions": [
                    ("can_approve_ticket", "Can approve ticket"),
                    ("can_reject_ticket", "Can reject ticket"),
                    ("can_view_all_tickets", "Can view all tickets"),
                ],
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
            },
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="error_file",
            field=models.FileField(
                blank=True,
                help_text="File containing error details",
                null=True,
                upload_to="bulk_uploads/errors/",
                verbose_name="error file",
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="started at"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the ticket was approved",
                null=True,
                verbose_name="approved at",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved this ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for ticket rejection (if applicable)",
                null=True,
                verbose_name="rejection reason",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="errors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of errors encountered during processing",
                verbose_name="errors",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="failed_records",
            field=models.IntegerField(
                default=0,
                help_text="Number of records that failed to process",
                verbose_name="failed records",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="file",
            field=models.FileField(
                help_text="CSV or Excel file containing ticket data",
                upload_to="bulk_uploads/%Y/%m/%d/",
                verbose_name="upload file",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="successful_records",
            field=models.IntegerField(
                default=0,
                help_text="Number of records successfully processed",
                verbose_name="successful records",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="total_records",
            field=models.IntegerField(
                default=0,
                help_text="Total number of records in the file",
                verbose_name="total records",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="upload_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="upload ID",
            ),
        ),
        migrations.AlterField(
            model_name="bulkupload",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the file",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_uploads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="age",
            field=models.IntegerField(
                help_text="Age must be between 8 and 19 years",
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(19),
                ],
                verbose_name="age",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="area",
            field=models.CharField(
                help_text="Church area within the zone",
                max_length=255,
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[("pre_teens", "Pre-Teens (8-12)"), ("teens", "Teens (13-19)")],
                help_text="Age category of the teen",
                max_length=20,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department within the church (optional)",
                max_length=255,
                null=True,
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True,
                help_text="Any dietary restrictions or allergies (optional)",
                null=True,
                verbose_name="dietary restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(
                help_text="Email address of the teen",
                max_length=255,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="emergency_contact",
            field=models.CharField(
                help_text="Name of emergency contact person",
                max_length=255,
                verbose_name="emergency contact name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="emergency_phone",
            field=models.CharField(
                help_text="Phone number of emergency contact",
                max_length=20,
                verbose_name="emergency contact phone",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="emergency_relationship",
            field=models.CharField(
                help_text="Relationship to the teen (e.g., Parent, Guardian)",
                max_length=100,
                verbose_name="emergency contact relationship",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="full_name",
            field=models.CharField(
                help_text="Full name of the teen",
                max_length=255,
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                help_text="Gender of the teen",
                max_length=20,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="medical_conditions",
            field=models.TextField(
                blank=True,
                help_text="Any existing medical conditions (optional)",
                null=True,
                verbose_name="medical conditions",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="medications",
            field=models.TextField(
                blank=True,
                help_text="Current medications (optional)",
                null=True,
                verbose_name="medications",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="parent_email",
            field=models.EmailField(
                help_text="Email address of parent or guardian",
                max_length=255,
                verbose_name="parent/guardian email",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="parent_name",
            field=models.CharField(
                help_text="Full name of parent or guardian",
                max_length=255,
                verbose_name="parent/guardian name",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="parent_phone",
            field=models.CharField(
                help_text="Phone number of parent or guardian",
                max_length=20,
                verbose_name="parent/guardian phone",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="parent_relationship",
            field=models.CharField(
                help_text="Relationship to the teen (e.g., Mother, Father, Guardian)",
                max_length=100,
                verbose_name="parent/guardian relationship",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="parish",
            field=models.CharField(
                help_text="Church parish name", max_length=255, verbose_name="parish"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone",
            field=models.CharField(
                help_text="Phone number of the teen",
                max_length=20,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="province",
            field=models.CharField(
                help_text="Church province", max_length=255, verbose_name="province"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image for ticket validation",
                null=True,
                upload_to="tickets/qr_codes/",
                verbose_name="QR code",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="registered_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the ticket was registered",
                verbose_name="registered at",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="registered_by",
            field=models.ForeignKey(
                help_text="User who registered this ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="registered by",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the ticket",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated unique ticket identifier",
                max_length=20,
                unique=True,
                verbose_name="ticket ID",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF version of the ticket",
                null=True,
                upload_to="tickets/pdfs/",
                verbose_name="ticket PDF",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="zone",
            field=models.CharField(
                help_text="Church zone within the province",
                max_length=255,
                verbose_name="zone",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_id"], name="tickets_tic_ticket__5a4a00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category"], name="tickets_tic_categor_fc7dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["approved_at"], name="tickets_tic_approve_c5bde7_idx"
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tickets.ticket",
                verbose_name="ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
