# Generated by Django 5.2.8 on 2025-12-03 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_province"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_in_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("qr_scan", "QR Scan"),
                            ("barcode", "Barcode Scan"),
                            ("nfc", "NFC Tap"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_records",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in Record",
                "verbose_name_plural": "Check-in Records",
                "ordering": ["-checked_in_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "checked_in_at"],
                        name="tickets_che_ticket__80d9cb_idx",
                    ),
                    models.Index(
                        fields=["checked_in_at"], name="tickets_che_checked_d738f4_idx"
                    ),
                    models.Index(
                        fields=["checked_in_by", "checked_in_at"],
                        name="tickets_che_checked_17760a_idx",
                    ),
                ],
            },
        ),
    ]
