# Generated by Django 5.2.8 on 2025-12-05 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_checkinrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Age must be at least 1 year."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Age must not exceed 100 years."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("toddler", "Toddler (1-5)"),
                    ("children_6_8", "Children (6-8)"),
                    ("pre_teens", "Pre-Teens (8-12)"),
                    ("teens", "Teens (13-19)"),
                    ("super_teens", "Super Teens"),
                    ("alumni", "Alumni"),
                    ("teacher", "Teacher/Volunteer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="province",
            field=models.CharField(
                choices=[
                    ("lagos_province_9", "Lagos Province 9"),
                    ("lagos_province_28", "Lagos Province 28"),
                    ("lagos_province_69", "Lagos Province 69"),
                    ("lagos_province_84", "Lagos Province 84"),
                    ("lagos_province_86", "Lagos Province 86"),
                    ("lagos_province_104", "Lagos Province 104"),
                    ("regional_hq", "Regional Headquarter"),
                ],
                max_length=255,
            ),
        ),
    ]
