# Generated by Django 5.2.8 on 2025-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_age_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('verification_pending', 'Verification Pending'), ('paid', 'Paid')], default='unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
