# Generated by Django 5.2.8 on 2025-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_payment_status_ticket_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
