# Generated by Django 5.2.8 on 2026-01-13 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_alter_ticket_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("camp", "Camp"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("retreat", "Retreat"),
                            ("concert", "Concert"),
                            ("outreach", "Outreach"),
                            ("other", "Other"),
                        ],
                        default="camp",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("venue", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "max_capacity",
                    models.IntegerField(default=0, help_text="0 = unlimited"),
                ),
                (
                    "current_registrations",
                    models.IntegerField(default=0, editable=False),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "early_bird_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Special price for early registration",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("early_bird_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/banners/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/thumbnails/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("registration_open", "Registration Open"),
                            ("registration_closed", "Registration Closed"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("waitlist", "Waitlist"),
                            ("checked_in", "Checked In"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("verification_pending", "Verification Pending"),
                            ("paid", "Paid"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tickets.event",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_registrations",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="tickets_eve_slug_8e284d_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="tickets_eve_status_3576f7_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type"], name="tickets_eve_event_t_727b1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date"], name="tickets_eve_start_d_67792c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["registration_start", "registration_end"],
                name="tickets_eve_registr_70d616_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="tickets_eve_event_i_acda85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registration_number"], name="tickets_eve_registr_989c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registered_at"], name="tickets_eve_registe_db1bdd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "ticket"), ("event", "user")},
        ),
    ]
