# Generated by Django 5.2.8 on 2026-09-02 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_delete_stale_event_eventregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(fields=["-timestamp"], name="ticketaudit_time_desc_idx"),
        ),
    ]
