"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os, sys, dj_database_url
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']

# Email-verification enforcement at login. Off by default (non-breaking); turn on
# once the verification email flow and frontend are ready. Foundation: is_verified
# field on User + /verify-email/ endpoint.
ENFORCE_EMAIL_VERIFICATION = os.getenv('ENFORCE_EMAIL_VERIFICATION', 'False').lower() == 'true'

# OTP (one-time codes). Provider-agnostic foundation; console backend by default.
# Point OTP_PROVIDER at a real SMS backend (Termii/Africa's Talking) to go live.
OTP_CODE_LENGTH = int(os.getenv('OTP_CODE_LENGTH', '6'))
OTP_TTL_SECONDS = int(os.getenv('OTP_TTL_SECONDS', '600'))
OTP_MAX_ATTEMPTS = int(os.getenv('OTP_MAX_ATTEMPTS', '5'))
OTP_PROVIDER = os.getenv('OTP_PROVIDER', 'users.otp_providers.ConsoleOTPProvider')

# Additive HttpOnly-cookie JWT auth (Bearer still accepted; header takes precedence).
# SameSite=Lax (default) neutralises cross-site CSRF for the cookie path. Enabling
# cross-site cookie auth (SameSite=None) requires a CSRF double-submit flow — deferred.
AUTH_COOKIE_ACCESS = os.getenv('AUTH_COOKIE_ACCESS', 'access_token')
AUTH_COOKIE_REFRESH = os.getenv('AUTH_COOKIE_REFRESH', 'refresh_token')
AUTH_COOKIE_SECURE = os.getenv('AUTH_COOKIE_SECURE', str(not DEBUG)).lower() == 'true'
AUTH_COOKIE_SAMESITE = os.getenv('AUTH_COOKIE_SAMESITE', 'Lax')
AUTH_COOKIE_DOMAIN = os.getenv('AUTH_COOKIE_DOMAIN') or None
# SameSite=None cookies are rejected by browsers unless Secure, and cross-site
# use also needs a CSRF double-submit flow (not yet implemented). Fail safe.
if AUTH_COOKIE_SAMESITE == 'None' and not AUTH_COOKIE_SECURE:
    import warnings
    warnings.warn('AUTH_COOKIE_SAMESITE=None requires Secure cookies; forcing AUTH_COOKIE_SECURE=True.')
    AUTH_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Registers the Postgres-only field and index types Scripture search needs
    # (SearchVectorField, GinIndex — see bible/search.py). The project is already
    # Postgres-only: some migrations use Postgres-specific SQL, and the test suite
    # runs against a local Postgres (see the DATABASES note below).
    'django.contrib.postgres',

    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # refresh-token revocation on logout/rotation
    'corsheaders',
    'drf_yasg',
    'drf_spectacular',
    'django_filters',
    'storages',
    'treebeard',

    # Local apps - Core
    'common',
    'hierarchy',
    'identity',
    'users',
    'profiles',
    'progress',  # Spiritual-action stream, streaks, Grace Days; foundational (depends on nothing)

    # Local apps - Content
    'bible',    # Scripture foundation; `content` depends on it, never the reverse
    'content',
    'media',  # Media & Podcasts app (uses label 'media_content' in apps.py)
    
    # Local apps - Events & Payments
    'events',
    'tickets',  # Legacy - will be deprecated after migration
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Cache
# IGNORE_EXCEPTIONS makes cache operations fail *open* (return None) instead of
# raising when Redis is unreachable. This matters now that DRF throttling is
# backed by this cache: a Redis blip must not turn every request into a 500 —
# it should degrade to "unthrottled" and keep serving. Ignored errors are logged.
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', default='redis://localhost:6379/0'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        }
    }
}
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL=os.getenv("DATABASE_URL")
if(DATABASE_URL):
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Run the test suite against a *local* Postgres.
#
# The dev DATABASE_URL points at a remote Neon instance ~184ms away. Django
# issues one round trip per SQL statement, so a suite that takes seconds locally
# takes tens of minutes there, and building the test database replays the whole
# migration history over that link. Pointing tests at localhost removes the
# latency multiplier entirely.
#
# Guarded on the `test` subcommand, not merely on the env var: a TEST_DATABASE_URL
# left in the environment must never redirect `runserver`, and above all never
# `migrate`, away from the real database. SQLite is not an option here — some
# migrations use Postgres-only SQL (e.g. profiles/0004 reads information_schema).
#
# Note `parse()`, not `config(default=...)`: config() reads the DATABASE_URL env
# var first and only falls back to `default` when it is unset, so it would
# silently ignore TEST_DATABASE_URL whenever DATABASE_URL is present.
def _running_tests():
    """
    True only for a test run — `manage.py test` or pytest.

    pytest cannot be detected from argv: `pytest` puts the test paths in
    sys.argv[1], and `python -m pytest` leaves `__main__.py` in sys.argv[0].
    But pytest-django imports this settings module from inside a live pytest
    process, so the `pytest` module is always in sys.modules by then — and no
    other management command imports it.
    """
    return sys.argv[1:2] == ['test'] or 'pytest' in sys.modules


TEST_DATABASE_URL = os.getenv('TEST_DATABASE_URL')
if TEST_DATABASE_URL and _running_tests():
    DATABASES['default'] = dj_database_url.parse(TEST_DATABASE_URL)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashing — bcrypt primary (per docs/15-technical-architecture.md: argon2/bcrypt).
# The first hasher is used for new/changed passwords; the rest remain available for
# *verifying* legacy hashes, so existing PBKDF2 passwords still work and are transparently
# upgraded to bcrypt on the user's next successful login. No forced resets.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# The timezone that defines a calendar day for daily content (today's devotional,
# Verse of the Day, reading-history day buckets). Storage stays UTC; only the
# day boundary is Nigerian. See docs/07-feature-specifications.md §8.
SCRIPTURE_TIMEZONE = os.getenv('SCRIPTURE_TIMEZONE', 'Africa/Lagos')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================
# CLOUDFLARE R2 MEDIA STORAGE
# ============================================================
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID')
R2_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', 'rccg-r63-media')
R2_PUBLIC_DOMAIN = os.getenv('R2_PUBLIC_DOMAIN', '').strip()
# Strip any protocol prefix the user may have accidentally included
R2_PUBLIC_DOMAIN = R2_PUBLIC_DOMAIN.replace('https://', '').replace('http://', '').strip('/')

if R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY and R2_ACCOUNT_ID:
    # Use Cloudflare R2 for all uploaded media files
    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com'
    AWS_S3_REGION_NAME = 'auto'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False  # Public URLs — no signed query strings
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    if R2_PUBLIC_DOMAIN:
        # Use your custom domain / R2 public bucket URL for file URLs
        AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_DOMAIN
        MEDIA_URL = f'https://{R2_PUBLIC_DOMAIN}/'
    else:
        MEDIA_URL = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com/{R2_BUCKET_NAME}/'

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    # Fall back to local storage when R2 credentials are not set
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings — raised for video files
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024   # 500MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Allowed file types for payment receipts
ALLOWED_RECEIPT_EXTENSIONS = ['.pdf', '.jpg', '.jpeg', '.png', '.gif']
MAX_RECEIPT_SIZE = 5 * 1024 * 1024  # 5MB


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import json
from uuid import UUID

class UUIDEncoder(json.JSONEncoder):
    """JSON encoder that converts UUID to string"""
    def default(self, obj):
        if isinstance(obj, UUID):
            return str(obj)
        return super().default(obj)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Superset of JWTAuthentication: header first, HttpOnly cookie fallback.
        'users.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'UPLOADED_FILES_USE_URL': True,
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate limiting (docs/15-technical-architecture.md: "Rate limiting per user/IP;
    # stricter on auth and OTP endpoints"). Global anon/user rates are generous so
    # normal browsing is unaffected; the 'auth' scope is reserved for login/OTP views
    # (attach `throttle_scope = 'auth'` on those views in a later phase).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '1000/min',
        'auth': '10/min',
        'otp': '5/min',
    },
}


# Custom User Model
AUTH_USER_MODEL = 'users.User'


# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Settings — open in dev, restricted to known origins in production
_cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '').strip()
if _cors_env and not DEBUG:
    CORS_ALLOW_ALL_ORIGINS = False
    import json as _json
    try:
        CORS_ALLOWED_ORIGINS = _json.loads(_cors_env)
    except (_json.JSONDecodeError, ValueError):
        CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_env.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = True

# Email Configuration - Brevo
MAILING = True

if MAILING:
    import sys
    # On Windows, Python's SSL bundle sometimes can't verify Brevo's cert via STARTTLS,
    # so we use a custom backend that disables cert verification as a workaround.
    # On Linux/Render, the standard backend works fine.
    if sys.platform == 'win32':
        EMAIL_BACKEND = 'backend.email_backend.BrevoEmailBackend'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    EMAIL_HOST = 'smtp-relay.brevo.com'
    # Port 587 + STARTTLS — Render (and most hosts) block port 465 outbound.
    EMAIL_PORT = 587
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('BREVO_SMTP_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('BREVO_SMTP_KEY', '')
    EMAIL_TIMEOUT = 30
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@r63teens.com')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    EMAIL_SUBJECT_PREFIX = '[R63 Teens] '

    # Multiple verified senders for different email contexts
    EMAIL_SENDERS = {
        'support': 'Faith Tribe Support <faithtribe.support@thefaithtribe.live>',
        'no_reply': 'No Reply <no-reply@thefaithtribe.live>',
        'junior_church': 'RCCG Junior Church <rccgjuniorchurch@thefaithtribe.live>',
        'default': DEFAULT_FROM_EMAIL,
    }
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email validation
if not os.environ.get('BREVO_SMTP_KEY') and MAILING:
    import warnings
    warnings.warn('BREVO_SMTP_KEY not set. Email functionality will not work.')

FRONTEND_URL = os.getenv("FRONTEND_URL")

# PayStack payment gateway
PAYSTACK_SECRET_KEY=os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY=os.getenv("PAYSTACK_PUBLIC_KEY")
FRONTEND_URL=os.getenv("FRONTEND_URL")

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'R63 API',
    'DESCRIPTION': 'R63 API description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_SPLIT_RESPONSE': True,
    # OTHER SETTINGS
}

# ==============================================================================
# CELERY SETTINGS
# ==============================================================================

CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat schedule is defined in backend/celery.py