# Generated by Django 5.2.8 on 2026-01-13 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("testimony", "Testimony"),
                            ("discussion", "Discussion"),
                            ("worship", "Worship"),
                            ("interview", "Interview"),
                            ("other", "Other"),
                        ],
                        default="teaching",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="podcasts/audio/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp3", "wav", "m4a", "ogg"]
                            )
                        ],
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Duration in HH:MM:SS format", null=True
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="podcasts/thumbnails/"
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                (
                    "guests",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of guests"
                    ),
                ),
                ("episode_number", models.IntegerField(blank=True, null=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("play_count", models.IntegerField(default=0, editable=False)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="content_pod_categor_370a00_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="content_pod_is_publ_45e62e_idx"
                    ),
                    models.Index(
                        fields=["published_at"], name="content_pod_publish_85ab6f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary for previews", max_length=500
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("testimony", "Testimony"),
                            ("education", "Education"),
                            ("inspiration", "Inspiration"),
                            ("news", "News"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("view_count", models.IntegerField(default=0, editable=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="content_art_slug_d82f31_idx"),
                    models.Index(
                        fields=["category"], name="content_art_categor_d0a60f_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="content_art_is_publ_3d120d_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="content_art_is_feat_f4f830_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Devotional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "scripture",
                    models.CharField(
                        help_text="Bible reference (e.g., John 3:16)", max_length=500
                    ),
                ),
                ("scripture_text", models.TextField(help_text="Full scripture text")),
                ("content", models.TextField(help_text="Main devotional content")),
                (
                    "prayer_points",
                    models.TextField(blank=True, help_text="Prayer points for the day"),
                ),
                ("memory_verse", models.CharField(blank=True, max_length=500)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="devotionals/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_devotionals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Devotional",
                "verbose_name_plural": "Devotionals",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="content_dev_date_775a2d_idx"),
                    models.Index(
                        fields=["is_published"], name="content_dev_is_publ_3ba861_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2020)]
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        help_text="Week number of the year (1-52)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("theme", models.CharField(max_length=255)),
                ("scripture_reference", models.CharField(max_length=500)),
                ("scripture_text", models.TextField()),
                ("lesson_content", models.TextField()),
                ("discussion_questions", models.TextField(blank=True)),
                ("practical_application", models.TextField(blank=True)),
                ("take_home_points", models.TextField(blank=True)),
                ("week_start", models.DateField(help_text="Sunday start date")),
                ("week_end", models.DateField(help_text="Saturday end date")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="manuals/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_manuals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual",
                "verbose_name_plural": "Manuals",
                "ordering": ["-year", "-week_number"],
                "indexes": [
                    models.Index(
                        fields=["year", "week_number"],
                        name="content_man_year_ef1942_idx",
                    ),
                    models.Index(
                        fields=["is_published"], name="content_man_is_publ_afa130_idx"
                    ),
                    models.Index(
                        fields=["week_start", "week_end"],
                        name="content_man_week_st_6fe3a2_idx",
                    ),
                ],
                "unique_together": {("year", "week_number")},
            },
        ),
    ]
