# Generated by Django 5.2.8 on 2026-01-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotional',
            name='bible_text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devotional',
            name='bible_text_passage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devotional',
            name='memory_verse_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devotional',
            name='memory_verse_passage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='anchor_scripture',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='key_point',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='scripture_text',
            field=models.TextField(blank=True),
        ),
    ]
