# Generated by Django 5.2.8 on 2026-03-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_devotional_bible_text_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="devotional",
            name="bible_in_one_year",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devotional",
            name="hymn",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="UserReadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "devotional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reads",
                        to="content.devotional",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devotional_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at"],
                "unique_together": {("user", "devotional")},
            },
        ),
    ]
