# Generated by Django 5.2.8 on 2026-04-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_add_likes_count_and_like_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="target_age_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave empty to show to all age groups",
            ),
        ),
        migrations.AddField(
            model_name="devotional",
            name="target_age_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave empty to show to all age groups. e.g. ['children', 'teen']",
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="discussion_guide",
            field=models.TextField(
                blank=True,
                help_text="Teacher-only discussion guide with prompts and answers",
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="has_teacher_edition",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="manual",
            name="teacher_notes",
            field=models.TextField(
                blank=True, help_text="Lesson plan notes visible to teachers only"
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="teacher_resources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Extra resource links/files for teachers",
            ),
        ),
        migrations.AlterField(
            model_name="manual",
            name="target_age_group",
            field=models.CharField(
                choices=[
                    ("all", "All Ages"),
                    ("children", "Children (6-8)"),
                    ("pre_teen", "Pre-Teen (9-12)"),
                    ("teen", "Teens (13-19)"),
                    ("superteen", "Superteen (19+)"),
                ],
                default="all",
                max_length=50,
            ),
        ),
    ]
