# Generated by Django 5.2.8 on 2026-07-09 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0001_initial"),
        ("content", "0005_article_target_age_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "devotional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_questions",
                        to="content.devotional",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["devotional", "order"],
                        name="content_dis_devotio_6c6a85_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemoryVerse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="The Verse of the Day. Exactly one per devotional.",
                    ),
                ),
                ("reference_display", models.CharField(max_length=255)),
                ("text_override", models.TextField(blank=True)),
                (
                    "devotional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_verses",
                        to="content.devotional",
                    ),
                ),
                (
                    "end_verse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for multi-verse memory passages.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_verse_ends",
                        to="bible.bibleverse",
                    ),
                ),
                (
                    "start_verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_verse_starts",
                        to="bible.bibleverse",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_verses",
                        to="bible.bibletranslation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Verse",
                "verbose_name_plural": "Memory Verses",
                "ordering": ["-is_primary", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["devotional", "is_primary"],
                        name="content_mem_devotio_31d715_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("devotional",),
                        name="content_one_primary_memory_verse",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScriptureReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("anchor", "Anchor Scripture"),
                            ("reading", "Bible Reading"),
                            ("cross_reference", "Cross Reference"),
                        ],
                        default="anchor",
                        max_length=20,
                    ),
                ),
                ("reference_display", models.CharField(max_length=255)),
                ("book_osis", models.CharField(db_index=True, max_length=20)),
                ("chapter_number", models.PositiveSmallIntegerField()),
                (
                    "start_verse_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "end_verse_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "devotional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripture_references",
                        to="content.devotional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scripture Reference",
                "verbose_name_plural": "Scripture References",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["devotional", "kind"],
                        name="content_scr_devotio_eaebdd_idx",
                    ),
                    models.Index(
                        fields=["book_osis", "chapter_number"],
                        name="content_scr_book_os_7e38a8_idx",
                    ),
                ],
            },
        ),
    ]
