# Generated by Django 5.2.8 on 2026-07-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_discussionquestion_memoryverse_scripturereference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved this. Never the same person as submitted_by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who submitted this for review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devotional",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devotional",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved this. Never the same person as submitted_by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devotional",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="devotional",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devotional",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who submitted this for review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manual",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved this. Never the same person as submitted_by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manual",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manual",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who submitted this for review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manualseries",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualseries",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved this. Never the same person as submitted_by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manualseries",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manualseries",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualseries",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who submitted this for review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="devotional",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manual",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manualseries",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
