# Generated by Django 5.2.8 on 2026-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_approved_at_article_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
