# Generated by Django 5.2.8 on 2026-07-09 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleBook",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("osis_code", models.CharField(db_index=True, max_length=20)),
                ("book_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                ("alternate_names", models.JSONField(blank=True, default=list)),
                (
                    "testament",
                    models.CharField(
                        choices=[("old", "Old Testament"), ("new", "New Testament")],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("chapter_count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Bible Book",
                "verbose_name_plural": "Bible Books",
                "ordering": ["translation", "book_number"],
            },
        ),
        migrations.CreateModel(
            name="BibleChapter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("verse_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="bible.biblebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible Chapter",
                "verbose_name_plural": "Bible Chapters",
                "ordering": ["book", "number"],
            },
        ),
        migrations.CreateModel(
            name="BibleTranslation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "language_code",
                    models.CharField(db_index=True, default="en", max_length=10),
                ),
                ("language_name", models.CharField(default="English", max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local", "Local (self-hosted)"),
                            ("remote", "Remote (API-fetched)"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("is_public_domain", models.BooleanField(default=False)),
                ("copyright_notice", models.TextField(blank=True)),
                ("license_source", models.CharField(blank=True, max_length=255)),
                ("attribution_required", models.BooleanField(default=False)),
                ("is_offline_capable", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Bible Translation",
                "verbose_name_plural": "Bible Translations",
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="bible_bible_is_acti_beb23e_idx",
                    ),
                    models.Index(
                        fields=["language_code"], name="bible_bible_languag_108232_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="bible_single_default_translation",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="biblebook",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="bible.bibletranslation",
            ),
        ),
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="bible.biblechapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible Verse",
                "verbose_name_plural": "Bible Verses",
                "ordering": ["chapter", "number"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="bible.biblechapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="bible.bibleverse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContinueReading",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verse_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="continue_reading_entries",
                        to="bible.biblechapter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_continue_reading",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Continue Reading Position",
                "verbose_name_plural": "Continue Reading Positions",
            },
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("pink", "Pink"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="bible.bibleverse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="bible.bibleverse",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_on", models.DateField(db_index=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to="bible.biblechapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_reading_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading History Entry",
                "verbose_name_plural": "Reading History",
                "ordering": ["-read_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("furthest_verse_number", models.PositiveSmallIntegerField(default=0)),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="bible.biblechapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Progress",
                "verbose_name_plural": "Reading Progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="biblechapter",
            index=models.Index(
                fields=["book", "number"], name="bible_bible_book_id_0f5d4b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="biblechapter",
            constraint=models.UniqueConstraint(
                fields=("book", "number"), name="bible_uniq_chapter"
            ),
        ),
        migrations.AddIndex(
            model_name="biblebook",
            index=models.Index(
                fields=["translation", "book_number"],
                name="bible_bible_transla_8533a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biblebook",
            index=models.Index(
                fields=["translation", "testament"],
                name="bible_bible_transla_f50e43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biblebook",
            index=models.Index(
                fields=["osis_code"], name="bible_bible_osis_co_2a1adf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="biblebook",
            constraint=models.UniqueConstraint(
                fields=("translation", "osis_code"), name="bible_uniq_book_osis"
            ),
        ),
        migrations.AddConstraint(
            model_name="biblebook",
            constraint=models.UniqueConstraint(
                fields=("translation", "book_number"), name="bible_uniq_book_number"
            ),
        ),
        migrations.AddIndex(
            model_name="bibleverse",
            index=models.Index(
                fields=["chapter", "number"], name="bible_bible_chapter_27af74_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bibleverse",
            constraint=models.UniqueConstraint(
                fields=("chapter", "number"), name="bible_uniq_verse"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-created_at"], name="bible_bookm_user_id_880e41_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("chapter__isnull", True), ("verse__isnull", False)),
                    models.Q(("chapter__isnull", False), ("verse__isnull", True)),
                    _connector="OR",
                ),
                name="bible_bookmark_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("verse__isnull", False)),
                fields=("user", "verse"),
                name="bible_uniq_bookmark_verse",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chapter__isnull", False)),
                fields=("user", "chapter"),
                name="bible_uniq_bookmark_chapter",
            ),
        ),
        migrations.AddIndex(
            model_name="highlight",
            index=models.Index(
                fields=["user", "-created_at"], name="bible_highl_user_id_6f8ebe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="highlight",
            constraint=models.UniqueConstraint(
                fields=("user", "verse"), name="bible_uniq_highlight"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "-updated_at"], name="bible_note_user_id_246213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "verse"], name="bible_note_user_id_85c801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readinghistory",
            index=models.Index(
                fields=["user", "-read_at"], name="bible_readi_user_id_48729b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readinghistory",
            index=models.Index(
                fields=["user", "read_on"], name="bible_readi_user_id_2e46bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(
                fields=["user", "is_completed"], name="bible_readi_user_id_8e090d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(
                fields=["user", "-updated_at"], name="bible_readi_user_id_64b744_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "chapter"), name="bible_uniq_progress"
            ),
        ),
    ]
