# Generated by Django 5.2.8 on 2026-07-14 11:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibleverse",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="bibleverse",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="bible_verse_search_gin"
            ),
        ),
    ]
