# Generated by Django 5.2.8 on 2026-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0002_bibleverse_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibletranslation",
            name="max_consecutive_verses",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Licence cap on consecutive verses shared at once. Blank = no cap.",
                null=True,
            ),
        ),
    ]
