# Generated by Django 5.2.8 on 2026-07-13 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritualAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("devotional_completed", "Devotional completed"),
                            ("chapter_read", "Bible chapter read"),
                            ("challenge_completed", "Challenge completed"),
                            ("journey_step_completed", "Journey step completed"),
                            ("verse_reviewed", "Memory verse reviewed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("occurred_on", models.DateField(db_index=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-occurred_at"],
                        name="progress_sp_user_id_b2aa18_idx",
                    ),
                    models.Index(
                        fields=["user", "occurred_on"],
                        name="progress_sp_user_id_d5e280_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StreakState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_length", models.PositiveIntegerField(default=0)),
                ("longest_length", models.PositiveIntegerField(default=0)),
                ("last_active_on", models.DateField(blank=True, null=True)),
                ("started_on", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="progress_st_user_id_5b594c_idx")
                ],
            },
        ),
    ]
