# Generated by Django 5.2.8 on 2026-07-13 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraceDayLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delta", models.SmallIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("monthly_allocation", "Monthly allocation"),
                            ("weekly_earned", "Earned: completed 7-day week"),
                            ("journey_earned", "Earned: completed Journey"),
                            ("streak_cover", "Consumed: covered a missed day"),
                        ],
                        max_length=32,
                    ),
                ),
                ("covered_on", models.DateField(blank=True, null=True)),
                ("effective_month", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grace_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="progress_gr_user_id_4bd7ed_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reason", "monthly_allocation")),
                        fields=("user", "effective_month"),
                        name="progress_one_monthly_allocation_per_month",
                    )
                ],
            },
        ),
    ]
