# Generated by Django 5.2.8 on 2026-07-13 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_gracedayledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gracedayledger",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", "monthly_allocation"), _negated=True),
                    ("effective_month__isnull", False),
                    _connector="OR",
                ),
                name="progress_monthly_allocation_has_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="gracedayledger",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", "streak_cover"), _negated=True),
                    ("delta__lt", 0),
                    _connector="OR",
                ),
                name="progress_streak_cover_is_negative",
            ),
        ),
    ]
