# Generated by Django 5.2.8 on 2026-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "progress",
            "0003_gracedayledger_progress_monthly_allocation_has_month_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="streakstate",
            name="active_days_this_week",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
