# Generated by Django 5.2.8 on 2026-07-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="hierarchy.hierarchynode",
            ),
        ),
    ]
