# Generated by Django 5.2.8 on 2026-07-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0002_alter_roleassignment_node"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roleassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="node",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="RoleAssignment",
        ),
    ]
