# Generated by Django 5.2.8 on 2025-12-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="ticket_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("toddler", "Toddler (1-5)"),
                    ("children_6_8", "Children (6-8)"),
                    ("pre_teens", "Pre-Teens (8-12)"),
                    ("teens", "Teens (13-19)"),
                    ("super_teens", "Super Teens"),
                    ("alumni", "Alumni"),
                    ("teacher", "Teacher/Volunteer"),
                ],
                help_text="Leave blank for all categories",
                max_length=20,
            ),
        ),
    ]
