# Generated by Django 5.2.8 on 2026-01-20 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media_categories/')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaSeries',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(upload_to='media_series/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='media_series_banners/')),
                ('host_name', models.CharField(max_length=255)),
                ('host_bio', models.TextField(blank=True)),
                ('host_image', models.ImageField(blank=True, null=True, upload_to='media_hosts/')),
                ('rss_feed_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('apple_podcasts_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('youtube_channel_url', models.URLField(blank=True)),
                ('release_frequency', models.CharField(blank=True, max_length=50)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('total_listen_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='media_content.mediacategory')),
            ],
            options={
                'verbose_name': 'Media Series',
                'verbose_name_plural': 'Media Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaEpisode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('show_notes', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='media_thumbnails/')),
                ('media_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video Only'), ('both', 'Audio & Video')], default='audio', max_length=10)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='media_audio/')),
                ('audio_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_mime_type', models.CharField(blank=True, max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to='media_video/')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('video_mime_type', models.CharField(blank=True, max_length=50)),
                ('video_resolution', models.CharField(blank=True, max_length=20)),
                ('hls_url', models.URLField(blank=True)),
                ('dash_url', models.URLField(blank=True)),
                ('embed_code', models.TextField(blank=True)),
                ('external_video_id', models.CharField(blank=True, max_length=100)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('guests', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True)),
                ('chapters', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_explicit', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media_content.mediaseries')),
            ],
            options={
                'verbose_name': 'Media Episode',
                'verbose_name_plural': 'Media Episodes',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistEpisode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.mediaepisode')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_content.playlist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='episodes',
            field=models.ManyToManyField(related_name='playlists', through='media_content.PlaylistEpisode', to='media_content.mediaepisode'),
        ),
        migrations.AddIndex(
            model_name='mediaseries',
            index=models.Index(fields=['status', 'created_at'], name='media_conte_status_058805_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaseries',
            index=models.Index(fields=['is_featured', 'status'], name='media_conte_is_feat_09a56b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaepisode',
            index=models.Index(fields=['series', 'episode_number'], name='media_conte_series__a3efc0_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaepisode',
            index=models.Index(fields=['status', 'published_at'], name='media_conte_status_73fe6e_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaepisode',
            index=models.Index(fields=['media_type'], name='media_conte_media_t_6adeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaepisode',
            index=models.Index(fields=['is_featured', 'status'], name='media_conte_is_feat_be30d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistepisode',
            unique_together={('playlist', 'episode')},
        ),
    ]
