# Generated by Django 5.2.8 on 2026-03-05 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaepisode",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="media_content.mediaseries",
            ),
        ),
        migrations.AlterField(
            model_name="mediaepisode",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="media_thumbnails/"
            ),
        ),
    ]
