# Generated by Django 5.2.8 on 2026-04-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_content", "0002_make_series_thumbnail_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaepisode",
            name="target_age_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave empty to show to all age groups",
            ),
        ),
        migrations.AddField(
            model_name="mediaseries",
            name="target_age_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave empty to show to all age groups",
            ),
        ),
    ]
