# Generated by Django 5.2.8 on 2026-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_content", "0003_mediaepisode_target_age_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaepisode",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mediaseries",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
