# Generated by Django 5.2.8 on 2026-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_content", "0004_alter_mediaepisode_status_alter_mediaseries_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaseries",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="media_series/"),
        ),
    ]
