# Generated by Django 5.2.8 on 2026-01-13 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeenProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("school", models.CharField(blank=True, max_length=255)),
                (
                    "grade_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jss1", "JSS 1"),
                            ("jss2", "JSS 2"),
                            ("jss3", "JSS 3"),
                            ("ss1", "SS 1"),
                            ("ss2", "SS 2"),
                            ("ss3", "SS 3"),
                            ("university", "University"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of interests"
                    ),
                ),
                (
                    "favorite_topics",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of favorite topics"
                    ),
                ),
                (
                    "devotional_reminder",
                    models.BooleanField(
                        default=True, help_text="Receive daily devotional reminders"
                    ),
                ),
                (
                    "new_content_notification",
                    models.BooleanField(
                        default=True, help_text="Receive notifications for new content"
                    ),
                ),
                (
                    "event_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for upcoming events",
                    ),
                ),
                (
                    "total_devotionals_read",
                    models.IntegerField(default=0, editable=False),
                ),
                (
                    "total_manuals_completed",
                    models.IntegerField(default=0, editable=False),
                ),
                (
                    "total_podcasts_played",
                    models.IntegerField(default=0, editable=False),
                ),
                ("current_streak", models.IntegerField(default=0, editable=False)),
                ("longest_streak", models.IntegerField(default=0, editable=False)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teen_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teen Profile",
                "verbose_name_plural": "Teen Profiles",
            },
        ),
        migrations.CreateModel(
            name="ContentProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, help_text="0-100 percentage"),
                ),
                (
                    "last_position",
                    models.DurationField(
                        blank=True, help_text="Last playback position", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Progress",
                "verbose_name_plural": "Content Progress Records",
                "ordering": ["-last_accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type"],
                        name="profiles_co_user_id_196f11_idx",
                    ),
                    models.Index(
                        fields=["status"], name="profiles_co_status_fef074_idx"
                    ),
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="SavedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("note", models.CharField(blank=True, max_length=500)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Content",
                "verbose_name_plural": "Saved Content",
                "ordering": ["-saved_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type"],
                        name="profiles_sa_user_id_82241b_idx",
                    )
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
