# Generated by Django 5.2.8 on 2026-01-20 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('age_group', models.CharField(blank=True, choices=[('toddler', 'Toddler (1-5)'), ('children', 'Children (6-7)'), ('pre_teen', 'Pre-Teen (8-12)'), ('teen', 'Teen (13-17)'), ('young_adult', 'Young Adult (18-19)')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Prefer not to say')], max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('province', models.CharField(choices=[('lagos_province_9', 'Lagos Province 9'), ('lagos_province_28', 'Lagos Province 28'), ('lagos_province_69', 'Lagos Province 69'), ('lagos_province_84', 'Lagos Province 84'), ('lagos_province_86', 'Lagos Province 86'), ('lagos_province_104', 'Lagos Province 104'), ('regional_hq', 'Regional Headquarter')], max_length=50)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('parish', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_relationship', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('favorite_devotional_topics', models.JSONField(blank=True, default=list)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('devotionals_read_count', models.PositiveIntegerField(default=0)),
                ('events_attended_count', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('last_devotional_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teen Profile',
                'verbose_name_plural': 'Teen Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_id', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_progress', to='profiles.teenprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('devotional', 'Devotional'), ('manual', 'Manual'), ('media_episode', 'Media Episode'), ('event', 'Event')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='profiles.teenprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevotionalProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('devotional_id', models.UUIDField()),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_progress', to='profiles.teenprofile')),
            ],
            options={
                'verbose_name': 'Devotional Progress',
                'verbose_name_plural': 'Devotional Progress',
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['province'], name='profiles_te_provinc_070650_idx'),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['age_group'], name='profiles_te_age_gro_c5eefc_idx'),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['parish'], name='profiles_te_parish_b66529_idx'),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['user'], name='profiles_te_user_id_420c31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manualprogress',
            unique_together={('profile', 'manual_id')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'content_type', 'content_id')},
        ),
        migrations.AlterUniqueTogether(
            name='devotionalprogress',
            unique_together={('profile', 'devotional_id')},
        ),
    ]
