# Generated by Django 5.2.8 on 2026-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teenprofile',
            name='profiles_te_age_gro_c5eefc_idx',
        ),
        migrations.RemoveField(
            model_name='teenprofile',
            name='age_group',
        ),
    ]
