# Generated by Django 5.2.8 on 2026-01-20 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_teenprofile_profiles_te_age_gro_c5eefc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teenprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('toddler', 'Toddler (1-5)'), ('children', 'Children (6-7)'), ('pre_teen', 'Pre-Teen (8-12)'), ('teen', 'Teen (13-17)'), ('young_adult', 'Young Adult (18-19)')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['age_group'], name='profiles_te_age_gro_c5eefc_idx'),
        ),
    ]
