# Generated by Antigravity - Safe migration to add gender column if missing
# This handles a production database state mismatch

from django.db import migrations


def add_gender_column_if_missing(apps, schema_editor):
    """
    Safely add the gender column if it doesn't exist.
    This fixes a state mismatch where Django thinks the migration is applied
    but the actual column is missing from the database.
    """
    connection = schema_editor.connection
    
    # Check if column already exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'profiles_teenprofile' 
            AND column_name = 'gender'
        """)
        if cursor.fetchone() is None:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE profiles_teenprofile 
                ADD COLUMN gender VARCHAR(20) DEFAULT 'not_specified' NOT NULL
            """)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - don't remove the column as it may contain data
    """
    pass  # No-op for safety


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_teenprofile_age_group_and_more'),
    ]

    operations = [
        migrations.RunPython(add_gender_column_if_missing, reverse_migration),
    ]
