# Generated by Antigravity - Comprehensive migration to add all missing TeenProfile columns
# This handles production database state mismatch where multiple columns are missing

from django.db import migrations


def add_missing_columns(apps, schema_editor):
    """
    Safely add all missing TeenProfile columns.
    Each column is checked individually before being added.
    """
    connection = schema_editor.connection
    
    # Define all columns that should exist with their SQL definitions
    # Format: (column_name, column_definition)
    columns_to_ensure = [
        ('gender', "VARCHAR(20) DEFAULT 'not_specified' NOT NULL"),
        ('bio', "TEXT DEFAULT '' NOT NULL"),
        ('avatar', "VARCHAR(100) NULL"),
        ('zone', "VARCHAR(100) DEFAULT '' NOT NULL"),
        ('area', "VARCHAR(100) DEFAULT '' NOT NULL"),
        ('department', "VARCHAR(255) DEFAULT '' NOT NULL"),
        ('emergency_contact_name', "VARCHAR(255) DEFAULT '' NOT NULL"),
        ('emergency_contact_phone', "VARCHAR(20) DEFAULT '' NOT NULL"),
        ('emergency_contact_relationship', "VARCHAR(100) DEFAULT '' NOT NULL"),
        ('medical_conditions', "TEXT DEFAULT '' NOT NULL"),
        ('allergies', "TEXT DEFAULT '' NOT NULL"),
        ('medications', "TEXT DEFAULT '' NOT NULL"),
        ('dietary_restrictions', "TEXT DEFAULT '' NOT NULL"),
        ('blood_group', "VARCHAR(10) DEFAULT '' NOT NULL"),
        ('favorite_devotional_topics', "JSONB DEFAULT '[]' NOT NULL"),
        ('notification_preferences', "JSONB DEFAULT '{}' NOT NULL"),
        ('devotionals_read_count', "INTEGER DEFAULT 0 NOT NULL"),
        ('events_attended_count', "INTEGER DEFAULT 0 NOT NULL"),
        ('streak_days', "INTEGER DEFAULT 0 NOT NULL"),
        ('longest_streak', "INTEGER DEFAULT 0 NOT NULL"),
        ('last_active_at', "TIMESTAMP WITH TIME ZONE NULL"),
        ('last_devotional_date', "DATE NULL"),
    ]
    
    with connection.cursor() as cursor:
        for column_name, column_definition in columns_to_ensure:
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'profiles_teenprofile' 
                AND column_name = %s
            """, [column_name])
            
            if cursor.fetchone() is None:
                # Column doesn't exist, add it
                sql = f"ALTER TABLE profiles_teenprofile ADD COLUMN {column_name} {column_definition}"
                try:
                    cursor.execute(sql)
                    print(f"Added missing column: {column_name}")
                except Exception as e:
                    print(f"Could not add column {column_name}: {e}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - don't remove columns as they may contain data
    """
    pass  # No-op for safety


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_safe_add_gender_column'),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, reverse_migration),
    ]
