# Generated by Django 5.2.8 on 2026-04-06 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_add_parish_and_guardian_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "eligible_age_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty = all age groups. e.g. ['children', 'pre_teen']",
                    ),
                ),
                ("coins_reward", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("requirement", models.TextField(blank=True)),
                ("eligible_age_groups", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("challenge_date", models.DateField(db_index=True)),
                (
                    "target_age_groups",
                    models.JSONField(
                        blank=True, default=list, help_text="Empty = all age groups"
                    ),
                ),
                ("coins_reward", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Daily Challenge",
                "verbose_name_plural": "Daily Challenges",
                "ordering": ["-challenge_date"],
            },
        ),
        migrations.CreateModel(
            name="FaithJourney",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("topic", models.CharField(blank=True, max_length=100)),
                ("total_steps", models.PositiveIntegerField(default=1)),
                (
                    "target_age_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty = all. e.g. ['teen', 'superteen']",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Faith Journey",
                "verbose_name_plural": "Faith Journeys",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("toddler", "Toddler (1-5)"),
                    ("children", "Children (6-8)"),
                    ("pre_teen", "Pre-Teen (9-12)"),
                    ("teen", "Teen (13-19)"),
                    ("superteen", "Superteen (19+)"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChildGameProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("mascot_style", models.CharField(default="default", max_length=50)),
                ("total_coins_earned", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_profile",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child Game Profile",
                "verbose_name_plural": "Child Game Profiles",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=50)),
                (
                    "assigned_age_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Age groups this teacher is assigned to e.g. ['children', 'pre_teen']",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_teachers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
            },
        ),
        migrations.CreateModel(
            name="DailyRewardClaim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claimed_date", models.DateField()),
                ("coins_awarded", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reward_claims",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Reward Claim",
                "verbose_name_plural": "Daily Reward Claims",
                "ordering": ["-claimed_date"],
                "unique_together": {("profile", "claimed_date")},
            },
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mood",
                    models.PositiveSmallIntegerField(
                        help_text="1=Very Sad, 2=Sad, 3=Neutral, 4=Happy, 5=Very Happy"
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=300)),
                ("entry_date", models.DateField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood Entry",
                "verbose_name_plural": "Mood Entries",
                "ordering": ["-entry_date"],
                "unique_together": {("profile", "entry_date")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awarded_to",
                        to="profiles.badge",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "ordering": ["-earned_at"],
                "unique_together": {("profile", "badge")},
            },
        ),
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awarded_to",
                        to="profiles.certificate",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_certificates",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Certificate",
                "verbose_name_plural": "User Certificates",
                "ordering": ["-earned_at"],
                "unique_together": {("profile", "certificate")},
            },
        ),
        migrations.CreateModel(
            name="UserJourneyProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("steps_completed", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="profiles.faithjourney",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_progress",
                        to="profiles.teenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Journey Progress",
                "verbose_name_plural": "User Journey Progress",
                "unique_together": {("profile", "journey")},
            },
        ),
    ]
