# Generated by Django 5.2.8 on 2026-04-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_badge_certificate_dailychallenge_faithjourney_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teenprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="guardian_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="guardian_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="parish",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="teenprofile",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lagos_province_9", "Lagos Province 9"),
                    ("lagos_province_28", "Lagos Province 28"),
                    ("lagos_province_69", "Lagos Province 69"),
                    ("lagos_province_84", "Lagos Province 84"),
                    ("lagos_province_86", "Lagos Province 86"),
                    ("lagos_province_104", "Lagos Province 104"),
                    ("regional_hq", "Regional Headquarter"),
                ],
                max_length=50,
            ),
        ),
    ]
