# Generated by Django 5.2.8 on 2025-12-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lagos_province_9", "Lagos Province 9"),
                    ("lagos_province_28", "Lagos Province 28"),
                    ("lagos_province_69", "Lagos Province 69"),
                    ("lagos_province_84", "Lagos Province 84"),
                    ("lagos_province_86", "Lagos Province 86"),
                    ("lagos_province_104", "Lagos Province 104"),
                    ("regional_hq", "Regional Headquarter"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
