# Generated by Django 5.2.8 on 2025-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("coordinator", "Coordinator"),
                    ("individual", "Individual"),
                ],
                default="coordinator",
                max_length=20,
            ),
        ),
    ]
