# Generated by Django 5.2.8 on 2026-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("coordinator", "Coordinator"),
                    ("individual", "Individual"),
                    ("teen", "Teen"),
                ],
                default="coordinator",
                max_length=20,
            ),
        ),
    ]
