# Generated by Django 5.2.8 on 2026-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("coordinator", "Coordinator"),
                    ("teen", "Teen"),
                    ("individual", "Individual"),
                ],
                default="teen",
                max_length=20,
            ),
        ),
    ]
