# Generated by Django 5.2.8 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_phone_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Email/phone ownership verified. Enforced at login only when settings.ENFORCE_EMAIL_VERIFICATION is on.",
            ),
        ),
    ]
