# Generated by Django 5.2.8 on 2026-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0010_otpcode"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_usernam_65d164_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_email_6f2530_idx",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-timestamp"], name="auditlog_time_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["-login_time"], name="loginhist_time_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "-login_time"], name="loginhist_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-date_joined"], name="user_date_joined_desc_idx"
            ),
        ),
    ]
