# Generated by Django 5.2.8 on 2025-12-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (e.g., CREATE, UPDATE, DELETE)",
                        max_length=255,
                        verbose_name="action",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity affected (e.g., user, ticket)",
                        max_length=50,
                        verbose_name="entity type",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="ID of the affected entity",
                        max_length=255,
                        verbose_name="entity ID",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Values before the change",
                        null=True,
                        verbose_name="old values",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="Values after the change",
                        null=True,
                        verbose_name="new values",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user who performed the action",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device information",
                        null=True,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the action was performed",
                        verbose_name="created at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["user"], name="audit_audit_user_id_292c79_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_2c1626_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                ],
            },
        ),
    ]
